### ISSUE TITLE
Slot Machine behavior fails (from the editor) without defined `slot_machine_rewards`

### ISSUE THREAD

**Issue by bunnymatic** [dorodango/doro#24]
In the gamestate editor, if I add a new entity that has the Slot Machine behavior and I try to use it, I get an error

```
[error] GenServer #PID<0.1811.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range, Stream
    (elixir) /private/tmp/elixir-20180316-64850-zsrybb/elixir-1.6.4/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /private/tmp/elixir-20180316-64850-zsrybb/elixir-1.6.4/lib/elixir/lib/enum.ex:193: Enumerable.slice/1
    (elixir) lib/enum.ex:2809: Enum.backwards_compatible_slice/1
    (elixir) lib/enum.ex:1792: Enum.random/1
    (doro) lib/doro/behaviors/slot_machine.ex:8: Doro.Behaviors.SlotMachine.handle/2
    (doro) lib/doro/session.ex:36: Doro.Session.handle_cast/2
```

Could we have a default `slot machine awards` that's built in there?  
Alternatively, you can't add a new item as a `slot machine` through the editor.
Alternatively, the front end gives you more inputs if you choose the `slot machine` behavior.

I wonder.  It feels like the last thing might become more important for actual development.  Other behaviors (like exit) require some follow up.  I've already looked into not showing `destination` chooser unless you add the `exit` behavior.  Maybe the smarts should go on the front end editor...

It means new behaviors that need new fancy options will need new fancy controls.

**Comment by bunnymatic** [comment]
Closing because with the new behavior refactor this is kinda moot.  for now...
